### PR TITLE
SCB-1598 Upgrade the docker plugin version to 0.31.0

### PR DESCRIPTION
**Pull request by WillemJiang**

### CODE REVIEW

**Comment by chanjarster** [comment]
I've noticed the CI build job failed, maybe [SCB-668](https://issues.apache.org/jira/browse/SCB-668) could give a clue.

**Comment by WillemJiang** [comment]
@chanjarster  Yes, I saw the issue that you reported. 
Once I remove the port check,  the docker  process is started rightly.
We may need to hold this PR for the new docker plugin release.

**Comment by zhfeng** [comment]
@WillemJiang is there any benefit from upgrading to 0.31.0 ?

**Comment by WillemJiang** [comment]
@zhfeng  Not exactly.  I think we can wait for the new release of docker plugin.

**Pull request closed without merging**
