### PR TITLE
[SCB-1281] Allows alpha's restful API to be accessed by CORS

### PR DESCRIPTION
**Pull request by coolbeevip**
Configuration parameter alpha.rest.cors.enabled=true

You can run a script test in the chrome console
```javascript
var xhr = new XMLHttpRequest();
xhr.open('GET','http://0.0.0.0:8090/saga/stats');
xhr.send(null);
xhr.onload = function(e){
	var xhr = e.target;
	console.log(xhr.responseText);
}
```

### CODE REVIEW

**Comment by WillemJiang** [comment]
I think we could fix it by hosting the front-end UI with the REST API provider at the same time.

**Comment by coolbeevip** [comment]
> I think we could fix it by hosting the front-end UI with the REST API provider at the same time.

Do you mean using a reverse proxy?

**Comment by coolbeevip** [comment]
issues #462

**Comment by WillemJiang** [comment]
> > I think we could fix it by hosting the front-end UI with the REST API provider at the same time.
> 
> Do you mean using a reverse proxy?

How about we put web module into site resource of alpha server?  In this way we can host the front-end UI through alpha server restful service.

**Pull request merged**
