### PR TITLE
fix the bug of alpha server printing  error log

### PR DESCRIPTION
**Pull request by tnessn**

### CODE REVIEW

**Comment by WillemJiang** [comment]
Could you explain the reason that you made these changes?

**Comment by zhfeng** [comment]
Thanks @tnessn for your contribution. Please raise an issue at [Serivecomb JIRA](https://issues.apache.org/jira/projects/SCB/issues) at first and describe what the bug is ?
This could be very helpful for us tracking the bugs.

**Comment by tnessn** [comment]
image
print these logs  frequently when alpha server start

**Comment by coolbeevip** [comment]
> image
> print these logs frequently when alpha server start

AlphaUI can only work in state machine mode[1], Is your Alpha working in state machine mode?

[1]https://github.com/apache/servicecomb-pack/blob/master/docs/fsm/fsm_manual.md

**Comment by tnessn** [comment]
> > image
> > print these logs frequently when alpha server start
> 
> AlphaUI can only work in state machine mode[1], Is your Alpha working in state machine mode?
> 
> [1]https://github.com/apache/servicecomb-pack/blob/master/docs/fsm/fsm_manual.md

Yes

**Comment by coolbeevip** [comment]
I think the systemInfo isn't empty in ${systemInfo.cpus}, Can you provide Alpha startup command and a more complete log?

**Comment by tnessn** [comment]
`nohup java -Dloader.path=./plugins -jar alpha-server-0.5.0-exec.jar  --spring.datasource.url=jdbc:mysql://172.31.132.184:3306/saga?serverTimezone=Asia/Shanghai\&useSSL=false\&allowPublicKeyRetrieval=true  --spring.datasource.username=saga --spring.datasource.password=xxx --eureka.client.enabled=true --eureka.client.service-url.defaultZone=http://172.31.132.162:8761/eureka/ --server.port=8111 --alpha.server.port=8112 --alpha.feature.akka.enabled=true --alpha.feature.akka.transaction.repository.type=elasticsearch --spring.data.elasticsearch.cluster-name=elasticsearch --spring.data.elasticsearch.cluster-nodes=172.31.132.147:9300 --spring.profiles.active=mysql --spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver >/dev/null 2>nohup.out &`

**Comment by coolbeevip** [comment]
> `nohup java -Dloader.path=./plugins -jar alpha-server-0.5.0-exec.jar --spring.datasource.url=jdbc:mysql://172.31.132.184:3306/saga?serverTimezone=Asia/Shanghai\&useSSL=false\&allowPublicKeyRetrieval=true --spring.datasource.username=saga --spring.datasource.password=xxx --eureka.client.enabled=true --eureka.client.service-url.defaultZone=http://172.31.132.162:8761/eureka/ --server.port=8111 --alpha.server.port=8112 --alpha.feature.akka.enabled=true --alpha.feature.akka.transaction.repository.type=elasticsearch --spring.data.elasticsearch.cluster-name=elasticsearch --spring.data.elasticsearch.cluster-nodes=172.31.132.147:9300 --spring.profiles.active=mysql --spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver >/dev/null 2>nohup.out &`

I cannot reproduce this problem on version 0.5.0, 

The getSystemInfo () method cannot return an empty object unless this method throws an exception. Can you give a log of all startup processes?

```
@Controller
public class IndexController implements ErrorController {

  @Autowired
  MetricsEndpoint metricsEndpoint;

  // index
  @GetMapping("/admin")
  public String index(ModelMap map) {
    map.put("systemInfo", getSystemInfo());
    return "index";
  }
```

**Pull request closed without merging**
